name: Deploy Auto-Posts-Bot

on:
  push:
    branches:
      - main # перевір, чи у тебе main, чи master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # Переходимо в папку проекту або клонуємо її, якщо це перший раз
            if [ ! -d "~/auto-posts-bot" ]; then
              git clone https://github.com/${{ github.repository }}.git ~/auto-posts-bot
              cd ~/auto-posts-bot
            else
              cd ~/auto-posts-bot
              git pull origin main
            fi
            
            # Встановлюємо залежності
            npm install
            
            # Запускаємо або перезапускаємо бота в PM2 через головний index.js
            pm2 restart "auto-posts-bot" --update-env || pm2 start index.js --name "auto-posts-bot"